### ISSUE TITLE
Permission Endpoints

### ISSUE THREAD

**Issue by pumbas600** [UoaWDCC/AEYB#7]
### Outcome

AEYB admins will be able to:
- Give/remove roles from users.
- View the roles for each user
- Get all possible permissions
- Edit the permissions for each role
- Create new roles / delete roles (Maybe have it so that they can only delete a role if there is no-one that has it though)
no one

### Moment

Endpoints that allow admins to view/edit/create/delete roles and edit/view roles of users

### Key Results

- [x] GET all possible permissions
- [x] CRUD endpoints for roles (MVP version)
- [x] CRUD endpoints for roles (nice to have version eg: extra delete functionality)
- [x] Permissions exist to restrict endpoints to admins only
- [x] Give users a role
- [x] View all roles a user has
- [x] Remove a role from users
- [x] GET count of users with role (Not sure if this is something that should be stored in the database or just calculated as needed)

**Comment by lpar105** [comment]
Question about "delete roles (Maybe have it so that they can only delete a role if there is no-one that has it though)"

I'm not 100% sure this will lead to the best user experience. Might be extremely annoying to search through a ton of user profiles to then remove a role from everyone if you want to delete a role at the end of the event etc. 

Perhaps it would be better to display a warning saying some people still have this role are you sure you want to delete?

**Comment by pumbas600** [comment]
> Perhaps it would be better to display a warning saying some people still have this role are you sure you want to delete?

Yeah, that's a great idea :))

**Comment by lpar105** [comment]
As an note: If any of the rest of the backend team are looking for more tasks to self assign to I can leave the tasks relating to users for someone else to add in. 

eg: give users a role, remove a role from users, get number of users with role, extra delete functionality
